# Generated by Django 5.2.4 on 2025-07-30 10:40

import django.contrib.postgres.fields.ranges
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0001_versioning_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('content', models.TextField()),
                ('sent_after', models.DateTimeField(null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.expressions.RawSQL('CURRENT_TIMESTAMP', []))),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('version', models.IntegerField(db_default=1, default=1)),
                ('sys_period', django.contrib.postgres.fields.ranges.DateTimeRangeField(db_default=django.db.models.expressions.RawSQL('TSTZRANGE(CURRENT_TIMESTAMP, null)', []))),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='cst_version_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('hid', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(null=True)),
                ('address', models.TextField(null=True)),
                ('version', models.IntegerField(null=True)),
                ('sys_period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
            ],
            options={
                'verbose_name': 'Customer (History)',
                'verbose_name_plural': 'Customers (History)',
                'indexes': [models.Index(fields=['sys_period'], name='csth_sys_period_idx')],
            },
        ),
    ]
