#!/usr/bin/env -S uv run --script

import subprocess
import os

runserver = subprocess.Popen(["python", "manage.py", "runserver"], env=os.environ)
meiliesearch = subprocess.Popen(["./meilisearch-linux-amd64"], env=os.environ)
ollamaserve = subprocess.Popen(["ollama", "serve"], env=os.environ)

try:
    runserver.wait()
    meiliesearch.wait()
    ollamaserve.wait()
except KeyboardInterrupt:
    runserver.kill()
    meiliesearch.kill()
    ollamaserve.kill()
    print("Bye.")
