#!/usr/bin/env bash

podman container run \
	--rm \
	--name simp \
	--mount type=bind,src="$(pwd)/docker-entrypoint.d/",dst=/docker-entrypoint.d/ \
	--mount type=bind,src="$(pwd)/",dst=/app/ \
	--publish 8080:80 \
	simp