version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Containerfile
      tags:
        - simp
    ports: 8000:80
    volumes:
      - ./docker-entrypoint.d:/docker-entrypoint.d/
      - ./:/app/
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      OLLAMA_HOST: "ollama"
      OLLAMA_PORT: "11434"

  db:
    image: docker.io/postgres:17
    ports: 5433:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: simp
      POSTGRES_PASSWORD: simp
      POSTGRES_DB: simp
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data

  meili:
    image: docker.io/getmeili/meilisearch:v1.15
    ports: 7700:7700

  ollama:
    image: docker.io/ollama/ollama
    ports: 11434:11434
    volumes:
      - ~/.ollama/:/root/.ollama