# Generated by Django 5.2.4 on 2025-07-28 11:21
# python manage.py makemigrations core --name customer_versioning_trigger --empty

from django.db import migrations

SQL = """
DROP TRIGGER IF EXISTS versioning_trigger ON core_customer;
CREATE TRIGGER versioning_trigger
BEFORE INSERT OR UPDATE OR DELETE ON core_customer
FOR EACH ROW EXECUTE PROCEDURE versioning(
  'sys_period',             -- sys_period
  'core_customerhistory',   -- history_table
  false,                    -- mitigate_update_conflicts
  false,                    -- ignore_unchanged_values
  false,                    -- include_current_version_in_history
  false,                    -- enable_migration_mode
  true,                     -- increment_version
  'version'                 -- version_column_name
);
"""

REVERSE_SQL = "DROP TRIGGER IF EXISTS versioning_trigger ON core_customer;"


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [migrations.RunSQL(SQL, REVERSE_SQL)]
